new Vue({
    el:"#root",
    data:{
        title:"哈哈哈",
        status:false,
        datas:[{
            title:"时尚时尚最时尚",
            id:1,
        },
        {
            title:"加油加油你最棒",
            id:2,
        },
        {
            title:"加油加油你最强",
            id:3,
        },
        {
            title:"搜索搜索",
            id:4,
        }
        ],
    },
    methods:{
        aa(){
           this.status=true;
        },
        bb(val){
           this.title=val;
           this.status=false;
        }
    }
})